name:                "relativ-frames"
version:             "0.1.0.0"
github:              "lgastako/relativ-frames"
license:             "BSD3"
author:              "John Evans"
maintainer:          "lgastako@gmail.com"
copyright:           "2022 John Evans"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            "Data Frames built on Relativ Indexes"
category:            "Data"

description:         "README at <https://github.com/lgastako/relativ-frames#readme>"

dependencies:
- base               >= 4.7 && < 5
- split
- relativ
- row-types
- vector-sized

library:
  source-dirs: src

tests:
  relativ-frames-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - relativ-frames
