name:                tdf
version:             0.1.0.0
github:              "lgastako/tdf"
license:             BSD3
author:              "John Evans"
maintainer:          "lgastako@gmail.com"
copyright:           "2022 John Evans"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Typed Data Frames
category:            Data

description:         README at <https://github.com/lgastako/tdf#readme>

ghc-options:
- -Wall

dependencies:
- base            >= 4.7 && < 5
- containers
- deepseq
- fin
- protolude
- row-types
- text
- unordered-containers
- vec

# - ghc-datasize
# - ghc-heap      == 8.10.7

# - fixed-vector
# - row-types       >= 1.0.0.0
# - vector

library:
  source-dirs: src

# executables:
#   tdf:
#     main:                Main.hs
#     source-dirs:         app
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - tdf

tests:
  tdf-test:
    main:                Driver.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tdf
    - tasty
    - tasty-quickcheck
    - tasty-discover
    - tasty-hedgehog
    - tasty-hspec
