name:                tdf
version:             0.1.0.0
github:              "lgastako/tdf"
license:             BSD3
author:              "John Evans"
maintainer:          "lgastako@gmail.com"
copyright:           "2022 John Evans"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Typed Data Frames
category:            Data

description:         README at <https://github.com/lgastako/tdf#readme>

ghc-options:
- -Wall
- -freduction-depth=0

dependencies:



- base                    >= 4.7 && < 5
- containers
- deepseq
- fakedata
- fin
- finite-typelits
- generic-lens
- lens
- mersenne-random
- mtl
- primitive
- protolude
- row-types
- semigroupoids
- text
- type-natural
- unordered-containers
- vec
- vec-lens
- vector
- vector-sized

library:
  source-dirs: src

tests:
  tdf-test:
    main:                Driver.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - QuickCheck
    - tdf
    - tasty
    - tasty-quickcheck
    - tasty-discover
    - tasty-hedgehog
    - tasty-hspec
    - quickcheck-text
    - quickcheck-classes
