name:                relativ-massiv
version:             0.1.0.0
github:              "lgastako/relativ-massiv"
license:             BSD3
author:              "John Evans"
maintainer:          "lgastako@gmail.com"
copyright:           "2022 John Evans"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            An attempt at frames via Massiv to check out massiv.
category:            Data

description:         README at <https://github.com/lgastako/relativ-massiv#readme>

dependencies:
- base >= 4.7 && < 5
- relativ
- massiv

library:
  source-dirs: src

tests:
  relativ-massiv-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - relativ-massiv
