name:                tdf-tools
version:             0.1.0.0
github:              "lgastako/tdf-tools"
license:             BSD3
author:              "John Evans"
maintainer:          "lgastako@gmail.com"
copyright:           "2022 John Evans"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            "Tools for manipulating DataFrames from the 'tdf' package."
category:            Data

description:         README at <https://github.com/lgastako/tdf-tools#readme>

dependencies:
- base >= 4.7 && < 5
- tdf
- time

library:
  source-dirs: src

tests:
  tdf-tools-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tdf-tools
