name:                torched
version:             0.1.0.0
github:              "lgastako/torched"
license:             BSD3
author:              "John Evans"
maintainer:          "lgastako@gmail.com"
copyright:           "2022 John Evans"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Short description of your package
category:            Machine Learning

description:         README at <https://github.com/lgastako/torched#readme>

dependencies:
- base >= 4.7 && < 5
- hasktorch
- tdf

library:
  source-dirs: src

executables:
  torched:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - torched
    - optparse-applicative

tests:
  torched-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - torched
