name:                relative-frames
version:             0.1.0.0
github:              "lgastako/relative-frames"
license:             BSD3
author:              "John Evans"
maintainer:          "lgastako@gmail.com"
copyright:           "2022 John Evans"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Data Frames based on Relativ Indexes
category:            Data

description:         README at <https://github.com/lgastako/relative-frames#readme>

dependencies:
- base >= 4.7 && < 5
- relativ

library:
  source-dirs: src

tests:
  relative-frames-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - relative-frames
